FROM python:3.11-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
        curl \
        git \
        wget \
    && groupadd -g 1000 appuser || true \
    && useradd -m -u 1000 -g 1000 -s /bin/bash appuser \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /backend

RUN python -m pip install --upgrade pip setuptools wheel

COPY requirements.txt /backend/requirements.txt

RUN pip install -r requirements.txt

ENV PATH="/backend/.venv/bin:${PATH}"

COPY . /backend
RUN chown -R appuser:appuser /backend

USER appuser

ENTRYPOINT ["/backend/entrypoint.sh"]
CMD ["tail", "-f", "/dev/null"]